// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: project

#ifndef _PROJECT_UI_H
#define _PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "C:\Users\dekar\lvgl\lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Colorwheel1;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Spinbox1;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_Checkbox2;
extern lv_obj_t * ui_Checkbox3;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
